#!/bin/bash

WORK_DIR="/home/git/mirrors"
REPO_URL="$PWD"

if [ $(git rev-parse --is-bare-repository) = true ]
then
    REPO_NAME=$(basename "$PWD")
    REPO_NAME=${REPO_NAME%.git}
else
    REPO_NAME=$(basename $(readlink -nf "$PWD"/..))
fi

if [ -d "$WORK_DIR/$REPO_NAME" ]; then
    cd "$WORK_DIR/$REPO_NAME"
    unset GIT_DIR
    git pull -q
else
    cd "$WORK_DIR"
    git clone -q "$REPO_URL" "$REPO_NAME"
fi